### ISSUE TITLE
[BUG] can't open arm-x64 on Macbook Pro M1 Pro

### ISSUE THREAD

**Issue by yamyoume** [rubegartor/ReelSteady-Joiner#26] opened 2022-06-21 05:52 UTC
**Describe the bug**
I have a macbook pro with an M1 Pro chip running macOS Monterey version 12.4 
the arm x64 version is not working 
when I Right-Click and then open I get this 
![image](https://user-images.githubusercontent.com/31030392/174725733-7e3ab63b-6958-4f60-848c-c41e77792256.png)

**Comment by yamyoume** [comment] 2022-06-22 08:07
that is weird, I don't have any anti-virus software installed, usually, I just right-click then open these kinds of apps and they work. 
I'll ask a friend with an M1 pro to test it

**Comment by JetFPV** [comment] 2022-06-24 07:15
Hello,
I have same issue here on MacBook Pro M1. It works fine on X86 version but not optimized I guess.
Very handy software by the way, thanks a lot. By default, it would be nice if joined file end up in the video folder.

**Comment by vacekj** [comment] 2022-07-27 09:06
This might be due to bad signing or notarization from Apple. If I build and sign the latest master locally, I don't get the error.

**Comment by yamyoume** [comment] 2022-07-27 10:20
> This might be due to bad signing or notarization from Apple. If I build and sign the latest master locally, I don't get the error.

How do I build it locally?

**Comment by konzeptzwei** [comment] 2022-08-04 20:43
I have the same issue. The 1.2.5 version is also damaged on my machine. MacBook Pro (14", 2021), Apple M1 Max, 64 GB

**Comment by CalebeNP** [comment] 2022-08-07 23:14
This is a signing problem, just disable GateKeeper for ReelSteady Joiner and it'll work fine.
`sudo xattr -rd com.apple.quarantine /Applications/ReelSteady\ Joiner.app`

**Comment by yamyoume** [comment] 2022-08-08 00:54
Can confirm it works BUT i had to do 
`sudo xattr -d com.apple.quarantine /Applications/ReelSteady\ Joiner.app`
because it was complaining about "-r" not being a recognizable option
it would be nice it didn't require that though

**Comment by rubegartor** [comment] 2022-08-08 19:04
I have finally been able to reproduce the error on my computer, I am working on solving the problem as soon as possible because solving **this problem is not free for me.** (Fuck u Apple)
As others have commented so far, it can be fixed with the following command:
`sudo xattr -d com.apple.quarantine /Applications/ReelSteady\ Joiner.app`

**Comment by porfel** [comment] 2022-08-21 00:10
This issue also reproduce on x86-64, with .pkg installer - but now its reproduces when trying to open .pkg file. I guess this is... because fucking apple want to get money for valid signature, and only one way to fix this without pay - add notice to readme: "Open 'System Preferences' -> 'Security' -> 'Authorize'" (or any translation to english or another lanuage) for this software.

**Comment by rubegartor** [comment] 2022-08-21 10:03
> This issue also reproduce on x86-64, with .pkg installer - but now its reproduces when trying to open .pkg file. I guess this is... because fucking apple want to get money for valid signature, and only one way to fix this without pay - add notice to readme: "Open 'System Preferences' -> 'Security' -> 'Authorize'" (or any translation to english or another lanuage) for this software.

Yes, it is already added in the following section of the README: [https://github.com/rubegartor/ReelSteady-Joiner#troubleshooting-](https://github.com/rubegartor/ReelSteady-Joiner#troubleshooting-)

**Closed** 2022-09-07 21:43 UTC
Labels: bug
